[phases.setup]
commands = [
  "echo 'Setup phase: nothing special'"
]

[phases.install]
commands = [
  "bun install --dev",
  "nix-env -iA nixpkgs.nginx"
]

[phases.build]
commands = [
  "bun run build"
]

[phases.start]
commands = [
  "/root/.nix-profile/sbin/nginx -g 'daemon off;' -c /app/nginx.conf"
]


[env]
PORT = "80"

[publish]
dir = "build"
